# Site settings
#source: .
title: Clear Line Tech
email: saul@saulhoward.com
description: > # this means to ignore newlines until "baseurl:"
  We help organisations radically improve their web and mobile apps using modern web technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clearlinetech.com" # the base hostname & protocol for your site
twitter_username: saulhoward
github_username:  clearline

exclude: [vendor, bin]

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments
